apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- if .Values.ingress.tlsSecret }}
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- if .Values.ingress.letsEncrypt }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- else }}
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
        path: {{ .Values.ingress.path }}
{{- if .Values.ingress.tlsSecret }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tlsSecret }}
{{- end }}
