replicas: 1
image:
  name: javipolo/http-show-headers
  tag: latest

requests:
  cpu: 100m
  memory: 100M

ingress:
  class: traefik
  host: your-hostname.org
  path: /http-show-headers
  tlsSecret:
  letsEncrypt: true

debug: false

nodeSelector:
